#!/usr/bin/env python3
"""
Stories Bot CLI - Interaktive Konfiguration und Verwaltung.
"""
import os
import sys
import subprocess
from pathlib import Path


def get_env_path():
    """Get the path to .env file in current directory."""
    return Path.cwd() / ".env"


def load_env():
    """Load .env file into environment."""
    env_path = get_env_path()
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    os.environ[key.strip()] = value.strip().strip('"').strip("'")


def cmd_init():
    """Interactive setup wizard for .env file."""
    env_path = get_env_path()
    
    print("\n" + "="*60)
    print("  Stories Bot - Interactive Setup")
    print("="*60)
    
    if env_path.exists():
        print(f"\n  .env file already exists at: {env_path}")
        resp = input("  Overwrite? (y/N): ").strip().lower()
        if resp != "y":
            print("  Aborted.")
            return
    
    print("\n  I'll ask you a few questions to configure the bot.")
    print("  Press Enter to accept default values [in brackets].\n")
    
    # BOT_TOKEN
    print("  1. BOT_TOKEN")
    print("     Get this from @BotFather on Telegram")
    print("     Example: 1234567890:ABCdefGHIjklMNOpqrSTUvwxYZ")
    bot_token = input("     Token: ").strip()
    if not bot_token:
        print("     ERROR: Token is required!")
        return
    
    # API_ID
    print("\n  2. API_ID")
    print("     Get this from https://my.telegram.org/apps")
    print("     It's a number like: 12345678")
    api_id = input("     API ID: ").strip()
    if not api_id:
        print("     ERROR: API ID is required!")
        return
    
    # API_HASH
    print("\n  3. API_HASH")
    print("     Get this from https://my.telegram.org/apps")
    print("     It's a string like: 0123456789abcdef0123456789abcdef")
    api_hash = input("     API Hash: ").strip()
    if not api_hash:
        print("     ERROR: API Hash is required!")
        return
    
    # SESSION_NAME
    print("\n  4. SESSION_NAME")
    print("     Name for the session file (for userbot)")
    session_name = input("     Session name [stories_session]: ").strip()
    if not session_name:
        session_name = "stories_session"
    
    # Write .env file
    with open(env_path, "w") as f:
        f.write(f"# Stories Bot Configuration\n")
        f.write(f"# Generated by: stories-bot init\n\n")
        f.write(f"# Telegram Bot Token (from @BotFather)\n")
        f.write(f"BOT_TOKEN=\"{bot_token}\"\n\n")
        f.write(f"# Telegram API credentials (from https://my.telegram.org/apps)\n")
        f.write(f"API_ID={api_id}\n")
        f.write(f"API_HASH=\"{api_hash}\"\n\n")
        f.write(f"# Session name for userbot\n")
        f.write(f"SESSION_NAME=\"{session_name}\"\n")
    
    print(f"\n  ✓ Configuration saved to: {env_path}")
    print("\n  Next steps:")
    print("    1. Run: stories-bot login   (first time only)")
    print("    2. Run: stories-bot run     (start the bot)")
    print()


def cmd_run():
    """Run the stories bot (manager + publisher)."""
    load_env()
    
    # Check if .env exists
    if not get_env_path().exists():
        print("ERROR: .env file not found!")
        print("Run 'stories-bot init' first to create configuration.")
        sys.exit(1)
    
    # Check required vars
    required = ["BOT_TOKEN", "API_ID", "API_HASH"]
    missing = [var for var in required if not os.environ.get(var)]
    if missing:
        print(f"ERROR: Missing required environment variables: {', '.join(missing)}")
        print("Run 'stories-bot init' to configure.")
        sys.exit(1)
    
    # Import and run the bot
    from stories_bot import manager, publisher
    import asyncio
    
    print("\n  Starting Stories Bot...")
    print("  Press Ctrl+C to stop\n")
    
    # Run both manager and publisher
    async def main():
        # Start publisher in background
        pub_task = asyncio.create_task(publisher.main_loop())
        # Run manager (blocking)
        await manager.main()
    
    asyncio.run(main())


def cmd_login():
    """Interactive login for userbot (first time setup)."""
    load_env()
    
    if not get_env_path().exists():
        print("ERROR: .env file not found!")
        print("Run 'stories-bot init' first.")
        sys.exit(1)
    
    api_id = os.environ.get("API_ID")
    api_hash = os.environ.get("API_HASH")
    session_name = os.environ.get("SESSION_NAME", "stories_session")
    
    if not api_id or not api_hash:
        print("ERROR: API_ID and API_HASH required!")
        sys.exit(1)
    
    print("\n  Userbot Login")
    print("  You'll be asked for your phone number and verification code.")
    print()
    
    # Create login script
    login_script = f'''
import asyncio
from telethon import TelegramClient

async def main():
    client = TelegramClient(
        "{session_name}",
        api_id={api_id},
        api_hash="{api_hash}"
    )
    await client.start()
    me = await client.get_me()
    print(f"\\n  ✓ Logged in as: {{me.first_name}} ({{me.username}})")
    await client.disconnect()

asyncio.run(main())
'''
    
    # Write and run login script
    login_path = Path.cwd() / "_temp_login.py"
    with open(login_path, "w") as f:
        f.write(login_script)
    
    try:
        subprocess.run([sys.executable, str(login_path)], check=True)
    finally:
        login_path.unlink(missing_ok=True)


def cmd_help():
    """Show help message."""
    print("""
Stories Bot - Telegram Stories Publisher

Usage:
    stories-bot <command>

Commands:
    init     Interactive setup wizard (creates .env file)
    run      Start the bot (manager + publisher)
    login    First-time login for userbot
    help     Show this help message

Examples:
    stories-bot init      # First time setup
    stories-bot login     # Login userbot (first time)
    stories-bot run       # Start the bot

Configuration:
    After running 'stories-bot init', edit .env file if needed.
    The .env file should be in your working directory.
""")


def main():
    """Main entry point for CLI."""
    if len(sys.argv) < 2:
        cmd_help()
        return
    
    command = sys.argv[1].lower()
    
    commands = {
        "init": cmd_init,
        "run": cmd_run,
        "login": cmd_login,
        "help": cmd_help,
    }
    
    if command in commands:
        commands[command]()
    else:
        print(f"Unknown command: {command}")
        cmd_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
